/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface OpenOrder {
  'side' : Side,
  'orderId' : bigint,
  'quantity' : bigint,
  'price' : bigint,
}
export type Side = { 'buy' : null } |
  { 'sell' : null };
export interface _SERVICE {
  'cancelAllOpenOrders' : ActorMethod<[], undefined>,
  'cancelOneOrderTest' : ActorMethod<[], undefined>,
  'getBotStatus' : ActorMethod<[], boolean>,
  'getConfig' : ActorMethod<
    [],
    { 'intervalSeconds' : bigint, 'spreadBps' : bigint, 'numOrders' : bigint }
  >,
  'getLastGrid' : ActorMethod<[], Array<[string, bigint]>>,
  'getLastMidPrice' : ActorMethod<[], bigint>,
  'getOpenOrders' : ActorMethod<[], Array<OpenOrder>>,
  'setConfig' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'startBot' : ActorMethod<[], undefined>,
  'stopBot' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];