/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'cancelOneOrderTest' : IDL.Func([], [], []),
  'getBotStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getConfig' : IDL.Func(
      [],
      [
        IDL.Record({
          'intervalSeconds' : IDL.Nat,
          'spreadBps' : IDL.Nat,
          'numOrders' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getLastGrid' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getLastMidPrice' : IDL.Func([], [IDL.Nat], ['query']),
  'setConfig' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'startBot' : IDL.Func([], [], []),
  'stopBot' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'cancelOneOrderTest' : IDL.Func([], [], []),
    'getBotStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getConfig' : IDL.Func(
        [],
        [
          IDL.Record({
            'intervalSeconds' : IDL.Nat,
            'spreadBps' : IDL.Nat,
            'numOrders' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getLastGrid' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getLastMidPrice' : IDL.Func([], [IDL.Nat], ['query']),
    'setConfig' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'startBot' : IDL.Func([], [], []),
    'stopBot' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };