/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const LogEntry = IDL.Record({
  'message' : IDL.Text,
  'timestamp' : Time,
  'eventType' : IDL.Text,
});
export const Side = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const OpenOrder = IDL.Record({
  'side' : Side,
  'orderId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'open' : IDL.Null,
  'filled' : IDL.Null,
});
export const OrderId = IDL.Nat;
export const OrderEntry = IDL.Record({
  'status' : OrderStatus,
  'side' : Side,
  'orderId' : OrderId,
  'timestamp' : Time,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'cancelAllOpenOrders' : IDL.Func([], [], []),
  'cancelOneOrderTest' : IDL.Func([], [], []),
  'getActivityLog' : IDL.Func([], [IDL.Vec(LogEntry)], ['query']),
  'getBotStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getConfig' : IDL.Func(
      [],
      [
        IDL.Record({
          'intervalSeconds' : IDL.Nat,
          'spreadBps' : IDL.Nat,
          'numOrders' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getLastGrid' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getLastMidPrice' : IDL.Func([], [IDL.Nat], ['query']),
  'getOpenOrders' : IDL.Func([], [IDL.Vec(OpenOrder)], []),
  'getTradeHistory' : IDL.Func([], [IDL.Vec(OrderEntry)], ['query']),
  'setConfig' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'startBot' : IDL.Func([], [], []),
  'stopBot' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const LogEntry = IDL.Record({
    'message' : IDL.Text,
    'timestamp' : Time,
    'eventType' : IDL.Text,
  });
  const Side = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const OpenOrder = IDL.Record({
    'side' : Side,
    'orderId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'open' : IDL.Null,
    'filled' : IDL.Null,
  });
  const OrderId = IDL.Nat;
  const OrderEntry = IDL.Record({
    'status' : OrderStatus,
    'side' : Side,
    'orderId' : OrderId,
    'timestamp' : Time,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'cancelAllOpenOrders' : IDL.Func([], [], []),
    'cancelOneOrderTest' : IDL.Func([], [], []),
    'getActivityLog' : IDL.Func([], [IDL.Vec(LogEntry)], ['query']),
    'getBotStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getConfig' : IDL.Func(
        [],
        [
          IDL.Record({
            'intervalSeconds' : IDL.Nat,
            'spreadBps' : IDL.Nat,
            'numOrders' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getLastGrid' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getLastMidPrice' : IDL.Func([], [IDL.Nat], ['query']),
    'getOpenOrders' : IDL.Func([], [IDL.Vec(OpenOrder)], []),
    'getTradeHistory' : IDL.Func([], [IDL.Vec(OrderEntry)], ['query']),
    'setConfig' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'startBot' : IDL.Func([], [], []),
    'stopBot' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };