/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const LogEntry = IDL.Record({
  'message' : IDL.Text,
  'timestamp' : Time,
  'eventType' : IDL.Text,
});
export const DepositAccount = IDL.Record({
  'owner' : IDL.Principal,
  'account' : IDL.Vec(IDL.Nat8),
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'open' : IDL.Null,
  'filled' : IDL.Null,
});
export const Side = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const OrderId = IDL.Nat;
export const OrderEntry = IDL.Record({
  'status' : OrderStatus,
  'side' : Side,
  'orderId' : OrderId,
  'timestamp' : Time,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'cancelAllOpenOrders' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'cancelSingleOrder' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getActivityLog' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(LogEntry)],
      ['query'],
    ),
  'getBalances' : IDL.Func(
      [],
      [IDL.Record({ 'icpBalance' : IDL.Nat, 'ckbtcBalance' : IDL.Nat })],
      [],
    ),
  'getBotStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getConfig' : IDL.Func(
      [],
      [
        IDL.Record({
          'spreadPips' : IDL.Nat,
          'orderSize' : IDL.Nat,
          'intervalSeconds' : IDL.Nat,
          'numOrders' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getDepositAddr' : IDL.Func([], [DepositAccount], []),
  'getLastGrid' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getOpenOrders' : IDL.Func([], [IDL.Vec(OrderEntry)], ['query']),
  'getTradeHistory' : IDL.Func([], [IDL.Vec(OrderEntry)], ['query']),
  'healthCheck' : IDL.Func([], [IDL.Bool], ['query']),
  'startBot' : IDL.Func([], [], []),
  'stopBot' : IDL.Func([], [], []),
  'updateConfig' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const LogEntry = IDL.Record({
    'message' : IDL.Text,
    'timestamp' : Time,
    'eventType' : IDL.Text,
  });
  const DepositAccount = IDL.Record({
    'owner' : IDL.Principal,
    'account' : IDL.Vec(IDL.Nat8),
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'open' : IDL.Null,
    'filled' : IDL.Null,
  });
  const Side = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const OrderId = IDL.Nat;
  const OrderEntry = IDL.Record({
    'status' : OrderStatus,
    'side' : Side,
    'orderId' : OrderId,
    'timestamp' : Time,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'cancelAllOpenOrders' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'cancelSingleOrder' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getActivityLog' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(LogEntry)],
        ['query'],
      ),
    'getBalances' : IDL.Func(
        [],
        [IDL.Record({ 'icpBalance' : IDL.Nat, 'ckbtcBalance' : IDL.Nat })],
        [],
      ),
    'getBotStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getConfig' : IDL.Func(
        [],
        [
          IDL.Record({
            'spreadPips' : IDL.Nat,
            'orderSize' : IDL.Nat,
            'intervalSeconds' : IDL.Nat,
            'numOrders' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getDepositAddr' : IDL.Func([], [DepositAccount], []),
    'getLastGrid' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getOpenOrders' : IDL.Func([], [IDL.Vec(OrderEntry)], ['query']),
    'getTradeHistory' : IDL.Func([], [IDL.Vec(OrderEntry)], ['query']),
    'healthCheck' : IDL.Func([], [IDL.Bool], ['query']),
    'startBot' : IDL.Func([], [], []),
    'stopBot' : IDL.Func([], [], []),
    'updateConfig' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };