/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface LogEntry {
    message: string;
    timestamp: Time;
    eventType: string;
}
export interface DepositAccount {
    owner: Principal;
    account: Uint8Array;
}
export interface OrderEntry {
    status: OrderStatus;
    side: Side;
    orderId: OrderId;
    timestamp: Time;
    quantity: bigint;
    price: bigint;
}
export type OrderId = bigint;
export enum OrderStatus {
    cancelled = "cancelled",
    open = "open",
    filled = "filled"
}
export enum Side {
    buy = "buy",
    sell = "sell"
}
export interface backendInterface {
    cancelAllOpenOrders(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    cancelSingleOrder(orderId: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getActivityLog(count: bigint, page: bigint): Promise<Array<LogEntry>>;
    getBalances(): Promise<{
        icpBalance: bigint;
        ckbtcBalance: bigint;
    }>;
    getBotStatus(): Promise<boolean>;
    getConfig(): Promise<{
        spreadPips: bigint;
        orderSize: bigint;
        intervalSeconds: bigint;
        numOrders: bigint;
    }>;
    getDepositAddr(): Promise<DepositAccount>;
    getLastGrid(): Promise<Array<[string, bigint]>>;
    getOpenOrders(): Promise<Array<OrderEntry>>;
    getTradeHistory(): Promise<Array<OrderEntry>>;
    healthCheck(): Promise<boolean>;
    startBot(): Promise<void>;
    stopBot(): Promise<void>;
    updateConfig(newInterval: bigint, newSpread: bigint, newOrders: bigint, newOrderSize: bigint): Promise<void>;
}
import type { OrderEntry as _OrderEntry, OrderId as _OrderId, OrderStatus as _OrderStatus, Side as _Side, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async cancelAllOpenOrders(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelAllOpenOrders();
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelAllOpenOrders();
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async cancelSingleOrder(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelSingleOrder(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelSingleOrder(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivityLog(arg0: bigint, arg1: bigint): Promise<Array<LogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityLog(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityLog(arg0, arg1);
            return result;
        }
    }
    async getBalances(): Promise<{
        icpBalance: bigint;
        ckbtcBalance: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getBalances();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBalances();
            return result;
        }
    }
    async getBotStatus(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getBotStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBotStatus();
            return result;
        }
    }
    async getConfig(): Promise<{
        spreadPips: bigint;
        orderSize: bigint;
        intervalSeconds: bigint;
        numOrders: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConfig();
            return result;
        }
    }
    async getDepositAddr(): Promise<DepositAccount> {
        if (this.processError) {
            try {
                const result = await this.actor.getDepositAddr();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDepositAddr();
            return result;
        }
    }
    async getLastGrid(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastGrid();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastGrid();
            return result;
        }
    }
    async getOpenOrders(): Promise<Array<OrderEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenOrders();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenOrders();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradeHistory(): Promise<Array<OrderEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradeHistory();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradeHistory();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async healthCheck(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.healthCheck();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.healthCheck();
            return result;
        }
    }
    async startBot(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startBot();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startBot();
            return result;
        }
    }
    async stopBot(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.stopBot();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.stopBot();
            return result;
        }
    }
    async updateConfig(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateConfig(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateConfig(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_OrderEntry_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderEntry): OrderEntry {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Side_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Side): Side {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _OrderStatus;
    side: _Side;
    orderId: _OrderId;
    timestamp: _Time;
    quantity: bigint;
    price: bigint;
}): {
    status: OrderStatus;
    side: Side;
    orderId: OrderId;
    timestamp: Time;
    quantity: bigint;
    price: bigint;
} {
    return {
        status: from_candid_OrderStatus_n5(_uploadFile, _downloadFile, value.status),
        side: from_candid_Side_n7(_uploadFile, _downloadFile, value.side),
        orderId: value.orderId,
        timestamp: value.timestamp,
        quantity: value.quantity,
        price: value.price
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    open: null;
} | {
    filled: null;
}): OrderStatus {
    return "cancelled" in value ? OrderStatus.cancelled : "open" in value ? OrderStatus.open : "filled" in value ? OrderStatus.filled : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): Side {
    return "buy" in value ? Side.buy : "sell" in value ? Side.sell : value;
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderEntry>): Array<OrderEntry> {
    return value.map((x)=>from_candid_OrderEntry_n3(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
